#!/bin/bash

# Determine the directory of the "run" script
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Compile and run all .c files in the "src" directory
for file in "$script_dir"/src/*.c; do
    if [ -f "$file" ]; then
        "$script_dir/scripts/crun" -H "$file"
        echo
    fi
done
